# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from templates.res_rc import *


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(501, 600)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, -1, 500, 600))
        self.widget.setMinimumSize(QtCore.QSize(500, 600))
        self.widget.setMaximumSize(QtCore.QSize(600, 700))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 500, 600))
        self.label.setStyleSheet(
            "background-image: url(:/images/main_.jpg);\n" "border-radius: 10px;"
        )
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(70, 500, 360, 71))
        self.label_2.setStyleSheet(
            "background-color: rgba(0,0, 0, 120);\n" "border-radius: 20px;\n" ""
        )
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setGeometry(QtCore.QRect(40, 30, 421, 281))
        self.listWidget.setStyleSheet(
            "background-color: rgba(190, 25, 176, 25);\n"
            "border: 2px solid rgba(190, 25, 176, 170)"
        )
        self.listWidget.setObjectName("listWidget")
        self.sound_slider = QtWidgets.QSlider(self.widget)
        self.sound_slider.setGeometry(QtCore.QRect(150, 360, 221, 22))
        self.sound_slider.setStyleSheet("")
        self.sound_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sound_slider.setObjectName("sound_slider")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(115, 506, 271, 61))
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setStyleSheet(
            "QPushButton{\n"
            "background-color: rgba(162, 0, 190, 100);\n"
            "border: 2px solid rgba(222, 17, 219, 200);\n"
            "border-radius: 10px;\n"
            "padding: 10px;\n"
            "font-size: 22px;\n"
            "color: rgba(255, 255, 255, 250);\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "background-color: rgba(0, 0, 0, 100);\n"
            "}"
        )
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.prev_btn = QtWidgets.QPushButton(self.frame)
        self.prev_btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.prev_btn.setObjectName("prev_btn")
        self.horizontalLayout_3.addWidget(self.prev_btn)
        self.pause_btn = QtWidgets.QPushButton(self.frame)
        self.pause_btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pause_btn.setStyleSheet(
            "QPushButton{\n"
            "background-color: rgba(162, 0, 190, 100);\n"
            "border: 2px solid rgba(222, 17, 219, 200);\n"
            "border-radius: 10px;\n"
            "padding: 10px;\n"
            "font-size: 21px;\n"
            "color: rgba(255, 255, 255, 250);\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "background-color: rgba(0, 0, 0, 100);\n"
            "}"
        )
        self.pause_btn.setObjectName("pause_btn")
        self.horizontalLayout_3.addWidget(self.pause_btn)
        self.next_btn = QtWidgets.QPushButton(self.frame)
        self.next_btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout_3.addWidget(self.next_btn)
        self.sound_time_slider = QtWidgets.QSlider(self.widget)
        self.sound_time_slider.setGeometry(QtCore.QRect(19, 400, 461, 22))
        self.sound_time_slider.setStyleSheet(
            "QSlider::groove::horisontal{\n"
            "background-color: rgba(0, 0, 0, 70);\n"
            "border: 2px solid rgba(202, 0, 216, 150);\n"
            "border-radius: 5px;\n"
            "}\n"
            "\n"
            "QSlider::handle::horisontal{\n"
            "width: 13px;\n"
            "height: 40px;\n"
            "padding: 5px;\n"
            "background-color: rgba(202, 0, 216, 255);\n"
            "border: 2px solid;\n"
            "border-right-color: rgb(255, 255, 255);\n"
            "border-left-color: rgb(255, 255, 255);\n"
            "border-top-color: rgba(202, 0, 216, 200);\n"
            "border-bottom-color: rgba(202, 0, 216, 200);\n"
            "}"
        )
        self.sound_time_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sound_time_slider.setObjectName("sound_time_slider")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setGeometry(QtCore.QRect(40, 310, 241, 41))
        self.frame_2.setMouseTracking(True)
        self.frame_2.setStyleSheet(
            "QPushButton{\n"
            "background-color: rgba(162, 0, 190, 100);\n"
            "border: 2px solid rgba(222, 17, 219, 200);\n"
            "border-radius: 10px;\n"
            "font-size: 15px;\n"
            "color: rgba(255, 255, 255, 250);\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "background-color: rgba(0, 0, 0, 100);\n"
            "}"
        )
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.remove_btn = QtWidgets.QPushButton(self.frame_2)
        self.remove_btn.setObjectName("remove_btn")
        self.horizontalLayout_2.addWidget(self.remove_btn)
        self.add_btn = QtWidgets.QPushButton(self.frame_2)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_2.addWidget(self.add_btn)
        self.play_frame = QtWidgets.QFrame(self.widget)
        self.play_frame.setGeometry(QtCore.QRect(170, 430, 171, 61))
        self.play_frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.play_frame.setStyleSheet(
            "QPushButton{\n"
            "background-color: rgba(0, 0, 0, 0);\n"
            "border: 2px solid rgba(222, 17, 219, 0);\n"
            "border-radius: 10px;\n"
            "padding: 5px;\n"
            "font-size: 26px;\n"
            "color: rgba(222, 17, 219, 250);\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "background-color: rgba(0, 0, 0, 100);\n"
            "}"
        )
        self.play_frame.setObjectName("play_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.play_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stop_btn = QtWidgets.QPushButton(self.play_frame)
        self.stop_btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.stop_btn.setStyleSheet("font-size: 50px;\n" "padding: 10px;")
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout.addWidget(self.stop_btn)
        self.line = QtWidgets.QFrame(self.play_frame)
        self.line.setStyleSheet("background-color: rgba(222, 17, 219, 250);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.play_btn = QtWidgets.QPushButton(self.play_frame)
        self.play_btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.play_btn.setStyleSheet("font-size: 40px;")
        self.play_btn.setObjectName("play_btn")
        self.horizontalLayout.addWidget(self.play_btn)
        self.label.raise_()
        self.next_btn.raise_()
        self.prev_btn.raise_()
        self.play_btn.raise_()
        self.listWidget.raise_()
        self.add_btn.raise_()
        self.remove_btn.raise_()
        self.sound_slider.raise_()
        self.label_2.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.sound_time_slider.raise_()
        self.stop_btn.raise_()
        self.play_btn.raise_()
        self.play_frame.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AudioTok"))
        self.prev_btn.setText(_translate("Form", "<"))
        self.pause_btn.setText(_translate("Form", "||"))
        self.next_btn.setText(_translate("Form", ">"))
        self.remove_btn.setText(_translate("Form", "REMOVE"))
        self.add_btn.setText(_translate("Form", "ADD"))
        self.stop_btn.setText(_translate("Form", " ▋"))
        self.play_btn.setText(_translate("Form", "▶️"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
